Repository gradido/gradido, pull requests merged in 2023-10, with the labels that each got.

#3212 fix(database): update mariadb image name
  docker-compose.yml
  mariadb/Dockerfile
Labels: bug

#3205 chore(release): v1.23.3
  .github/workflows/test_admin_interface.yml
  .github/workflows/test_frontend.yml
  CHANGELOG.md
  admin/package.json
  backend/package.json
  database/package.json
  dht-node/package.json
  dlt-connector/package.json
  federation/package.json
  frontend/Dockerfile
  frontend/package.json
  frontend/yarn.lock
  package.json
Labels: release

#3216 feat(frontend): tunnel community UUId to send
  backend/src/graphql/resolver/CommunityResolver.ts
  backend/src/graphql/resolver/util/communities.ts
  frontend/src/components/GddSend/TransactionForm.spec.js
  frontend/src/components/GddSend/TransactionForm.vue
  frontend/src/graphql/queries.js
  frontend/src/pages/Send.vue
Labels: feature

#3215 feat(backend): x-com-sendcoins 31: insert recipient as foreign user in users table after x com sendcoins
  backend/src/config/index.ts
  backend/src/federation/client/1_0/model/SendCoinsArgs.ts
  backend/src/graphql/arg/TransactionSendArgs.ts
  backend/src/graphql/arg/UserArgs.ts
  backend/src/graphql/model/User.ts
  backend/src/graphql/resolver/TransactionResolver.test.ts
  backend/src/graphql/resolver/TransactionResolver.ts
  backend/src/graphql/resolver/UserResolver.test.ts
  backend/src/graphql/resolver/UserResolver.ts
  backend/src/graphql/resolver/util/communities.ts
  backend/src/graphql/resolver/util/findUserByIdentifier.ts
  backend/src/graphql/resolver/util/processXComSendCoins.ts
  backend/src/graphql/resolver/util/storeForeignUser.ts
  backend/src/seeds/factory/user.ts
  backend/src/seeds/graphql/queries.ts
  backend/src/util/communityUser.ts
  database/entity/0073-introduce_foreign_user_in_users_table/User.ts
  database/entity/User.ts
  database/migrations/0073-introduce_foreign_user_in_users_table.ts
  dht-node/src/config/index.ts
  e2e-tests/cypress/e2e/SendCoins.feature.save
  federation/src/config/index.ts
  federation/src/graphql/api/1_0/model/SendCoinsArgs.ts
  federation/src/graphql/api/1_0/resolver/SendCoinsResolver.test.ts
  federation/src/graphql/api/1_0/resolver/SendCoinsResolver.ts
  federation/src/graphql/api/1_0/util/storeForeignUser.ts
  federation/src/graphql/util/findUserByIdentifier.ts
  frontend/src/components/GddSend/TransactionForm.vue
  frontend/src/components/TransactionRows/Name.vue
  frontend/src/graphql/queries.js
Labels: service: wallet frontend, service: backend, service: database

#3221 docs(frontend): update news on wallet start page
  frontend/src/assets/News/news.json
  frontend/src/components/Overview/CommunityNews.vue
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/es.json
  frontend/src/locales/fr.json
  frontend/src/locales/nl.json
  frontend/src/locales/tr.json
Labels: docu

#3220 feat(federation): x-com-sendcoins 32: communtiy authentication handshake
  backend/src/federation/authenticateCommunities.ts
  backend/src/federation/client/1_0/AuthenticationClient.ts
  backend/src/federation/client/1_0/model/OpenConnectionArgs.ts
  backend/src/federation/client/1_0/query/openConnection.ts
  backend/src/federation/client/1_1/AuthenticationClient.ts
  backend/src/federation/client/AuthenticationClientFactory.ts
  backend/src/federation/validateCommunities.test.ts
  backend/src/federation/validateCommunities.ts
  backend/src/graphql/model/UserAdmin.ts
  backend/src/graphql/resolver/UserResolver.ts
  docu/Concepts/TechnicalRequirements/image/TechnicalOverview_V1-19.drawio.png
  federation/jest.config.js
  federation/package.json
  federation/src/client/1_0/AuthenticationClient.ts
  federation/src/client/1_0/query/authenticate.ts
  federation/src/client/1_0/query/openConnectionCallback.ts
  federation/src/client/1_1/AuthenticationClient.ts
  federation/src/client/AuthenticationClientFactory.ts
  federation/src/client/enum/ApiVersionType.ts
  federation/src/graphql/api/1_0/model/AuthenticationArgs.ts
  federation/src/graphql/api/1_0/model/OpenConnectionArgs.ts
  federation/src/graphql/api/1_0/model/OpenConnectionCallbackArgs.ts
  federation/src/graphql/api/1_0/resolver/AuthenticationResolver.ts
  federation/src/graphql/api/1_0/resolver/PublicCommunityInfoResolver.ts
  federation/src/graphql/api/1_0/resolver/PublicKeyResolver.ts
  federation/src/graphql/api/1_0/util/authenticateCommunity.ts
  federation/src/graphql/api/1_0/util/revertSettledReceiveTransaction.ts
  federation/src/graphql/api/1_0/util/settlePendingReceiveTransaction.ts
  federation/src/graphql/schema.ts
  federation/test/helpers.ts
  federation/test/testSetup.ts
  federation/yarn.lock
Labels: feature, service: backend, service: federation

#3222 feat(frontend): split admins and moderators on info page
  frontend/src/graphql/queries.js
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/es.json
  frontend/src/locales/fr.json
  frontend/src/locales/nl.json
  frontend/src/locales/tr.json
  frontend/src/pages/InfoStatistic.vue
Labels: feature
