Repository gradido/gradido, pull requests merged in 2025-05, with the labels that each got.

#3480 chore(release): v2.5.2 beta
  CHANGELOG.md
  admin/package.json
  backend/package.json
  database/package.json
  dht-node/package.json
  dlt-connector/package.json
  federation/package.json
  frontend/package.json
  package.json
Labels: release

#3482 feat(workflow): stop deploy script on error, always cleanup lock file
  .nvmrc
  admin/.nvmrc
  config/.nvmrc
  database/.nvmrc
  deployment/bare_metal/start.sh
  deployment/hetzner_cloud/migration/2_5_1-2_5_2/README.md
  deployment/hetzner_cloud/migration/2_5_1-2_5_2/upgradeNodeJs.sh
  dht-node/.nvmrc
  federation/.nvmrc
  frontend/.nvmrc
Labels: feature, devops

#3484 fix(backend): fix problem with humhub, changing from and to alias
  backend/src/apis/humhub/syncUser.ts
  backend/src/graphql/resolver/util/syncHumhub.ts
  frontend/src/locales/de.json
  frontend/src/locales/en.json
Labels: bug, service: backend, humhub

#3467 feat(workflow): x-cross tx per link
  backend/jest.config.js
  backend/package.json
  backend/src/auth/INALIENABLE_RIGHTS.ts
  backend/src/auth/RIGHTS.ts
  backend/src/auth/USER_RIGHTS.ts
  backend/src/auth/jwt/JWT.ts
  backend/src/auth/jwt/payloadtypes/DisburseJwtPayloadType.ts
  backend/src/auth/jwt/payloadtypes/JwtPayloadType.ts
  backend/src/auth/jwt/payloadtypes/RedeemJwtPayloadType.ts
  backend/src/config/index.ts
  backend/src/config/schema.ts
  backend/src/federation/client/1_0/FederationClient.ts
  backend/src/graphql/model/RedeemJwtLink.ts
  backend/src/graphql/model/TransactionLink.ts
  backend/src/graphql/model/User.ts
  backend/src/graphql/resolver/TransactionLinkResolver.ts
  backend/src/graphql/resolver/util/communities.ts
  backend/src/graphql/union/QueryLinkResult.ts
  docu/Concepts/TechnicalRequirements/image/redeemlink_without_community-switch.png
  frontend/src/components/CommunitySwitch.vue
  frontend/src/components/LinkInformations/RedeemCommunitySelection.vue
  frontend/src/components/LinkInformations/RedeemInformation.vue
  frontend/src/components/LinkInformations/RedeemSelectCommunity.vue
  frontend/src/components/LinkInformations/RedeemValid.vue
  frontend/src/graphql/mutations.js
  frontend/src/graphql/queries.js
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/pages/TransactionLink.spec.js
  frontend/src/pages/TransactionLink.vue
  frontend/src/pages/TransactionLinkDisburse.vue
Labels: feature

#3487 fix(other): correct bun install script
  deployment/bare_metal/start.sh
Labels: bug, devops

#3488 feat(other): split start script, put additional installs in extra script
  .github/file-filters.yml
  .github/workflows/test_deploy.yml
  deployment/bare_metal/Dockerfile
  deployment/bare_metal/install-missing-deps.sh
  deployment/bare_metal/start.sh
Labels: refactor, devops

#3490 fix(workflow): wrong database docker call
  .github/workflows/publish.yml
Labels: bug

#3493 feat(frontend): change experimental to beta
  frontend/src/locales/de.json
  frontend/src/locales/en.json
  frontend/src/locales/es.json
  frontend/src/locales/fr.json
  frontend/src/locales/nl.json
Labels: feature, service: wallet frontend

#3491 feat(frontend): use grass as faster alternative to sass
  admin/package.json
  admin/vite.config.mjs
  bun.lock
  deployment/bare_metal/Dockerfile
  deployment/bare_metal/install-missing-deps.sh
  deployment/bare_metal/start.sh
  frontend/README.md
  frontend/package.json
  frontend/scripts/scss.mjs
  frontend/vite.config.mjs
  yarn.lock
Labels: feature, service: wallet frontend, service: admin frontend

#3496 fix(admin): fix accidently remove user states
  admin/src/pages/UserSearch.vue
Labels: bug, service: admin frontend

#3500 fix(frontend): fix contribution link
  .vscode/launch.json
  frontend/src/components/LinkInformations/RedeemInformation.vue
  frontend/src/pages/TransactionLink.vue
  frontend/vite.config.mjs
Labels: bug, service: wallet frontend
